# Generated by Django 5.0.4 on 2024-05-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=10)),
                ('domingo', models.CharField(max_length=100)),
                ('segunda', models.CharField(max_length=100)),
                ('terca', models.CharField(max_length=100)),
                ('quarta', models.CharField(max_length=100)),
                ('quinta', models.CharField(max_length=100)),
                ('sexta', models.CharField(max_length=100)),
                ('sabado', models.CharField(max_length=100)),
            ],
        ),
    ]
