# Generated by Django 5.0.4 on 2024-04-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alunos',
            new_name='Aluno',
        ),
    ]
