# Generated by Django 5.0.4 on 2024-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0002_rename_alunos_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
            ],
        ),
    ]
