# Generated by Django 5.0.4 on 2024-04-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0003_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodo',
        ),
    ]
