# Generated by Django 5.0.4 on 2024-04-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0004_remove_aluno_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meteria',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='login',
            field=models.TextField(default='sem login', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.TextField(default='sem senha', max_length=50),
        ),
        migrations.CreateModel(
            name='Disponibilidade_Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.dia')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Materia_Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.aluno')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade_Dia_Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.dia')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.professor')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_qts.meteria')),
            ],
        ),
    ]
