# Generated by Django 5.0.4 on 2024-05-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qts', '0006_rename_meteria_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_professor',
            name='id_aluno',
        ),
        migrations.AddField(
            model_name='materia_professor',
            name='id_materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_qts.materia'),
            preserve_default=False,
        ),
    ]
